yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
] 

yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('/posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeDoneView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='users/password_reset_form.html'),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/about/models.py
from django.db import models

# Create your models here.

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(
        auto_now_add=True, verbose_name="Publication date"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )


class Meta:
    ordering = ['-pub_date']

yatube/users/models.py
from django.db import models

# Create your models here.

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

    def clean_text(self):
        data = self.cleaned_data['text']
        if '' not in data.lower():
            raise forms.ValidationError(
                'Вы обязательно должны заполнить это поле!'
            )
        return data

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group
from .forms import PostForm

LIMIT_POSTS = 10
LIMIT_LIST = 10


def index(request):
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, LIMIT_LIST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    posts = Post.objects.select_related()[:LIMIT_POSTS]
    context = {
        'page_obj': page_obj,
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, LIMIT_LIST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:LIMIT_POSTS]
    context = {
        'page_obj': page_obj,
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, LIMIT_LIST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, LIMIT_LIST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/post_detail.html', context)


def post_create(request):
    form = PostForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect('posts:profile', request.user.username)
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


def post_edit(request):
    form = PostForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect('posts:profile', request.user.username)
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})

yatube/users/views.py
# Импортируем CreateView, чтобы создать ему наследника
from django.views.generic import CreateView

# Функция reverse_lazy позволяет получить URL по параметрам функции path()
# Берём, тоже пригодится
from django.urls import reverse_lazy

# Импортируем класс формы, чтобы сослаться на неё во view-классе
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% include 'base.html' %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Тут я размещу информацию о себе, используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
</p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% include 'base.html' %}
{% block content %}
  <div class="row">
    <h1>Вот что я умею</h1>
    {% comment %}
      Боковой блок со списком технологий 
      Займет всю ширину блока на мобильном
      и 25% при размерах экрана ≥768px
    {% endcomment %}
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Python
        </li>
        <li class="list-group-item">
          Django
        </li>
      </ul>
    </aside>
    {% comment %}
      Статья  
      Займет всю ширину блока на мобильном
      и 75% при размерах экрана ≥768px
    {% endcomment %}
    <article class="col-12 col-md-9">
      <p>Текст страницы "Технологии"</p>
    </article>
  </div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html> 
<html lang="ru">          
  <head>
    {% load static %}
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Подключаем описание страницы для поисковиков -->
    <meta name="description" content="Интересные статьи">
    <!-- Загружаем фав-иконки -->
    <title>
    {% block title %}Последние обновления на сайте{% endblock %}
    </title>
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="manifest" href="/site.webmanifest">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <!-- Ссылка на статистические файлы -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Подключаем Bootstrap- предоставляет разработчику файл с готовыми CSS-стилями-->
    <link 
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" 
    rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" 
    crossorigin="anonymous">
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  {% include 'posts/includes/header.html' %}
  <main>
    <div class="container py-5">
      {% block content %}{% endblock %}
      {% include 'posts/includes/paginator.html' %}
    </div>
  </main>
  {% include 'posts/includes/footer.html' %}
</html>

yatube/templates/includes/card_post.html
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    <p>{{ post.text }}</p>
  </ul>
  {% if post.group %}
  <a href=" {% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
</article>

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
    {% if not is_edit %}
        Добавить запись
    {% else %}  
        Редактировать запись
    {% endif %}
{% endblock %}
{% include 'base.html' %}
{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
            <div class="card-header">       
                Новый пост             
            </div>
            <div class="card-body">        
                <form method="post" action="../posts/create_post.html">
                <input type="hidden" name="csrfmiddlewaretoken" value="">            
                <div class="form-group row my-3 p-3">
                    <label for="id_text">
                    Текст поста                  
                    <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                    Текст нового поста
                    </small>                  
                </div>
                {% if post.group %}   
                <a href="{% url 'posts:profile' post.author.username %}">Лев Толстой – зеркало русской революции</a>            
                    <div class="form-group row my-3 p-3">
                        <label for="id_group">
                        Группа                  
                        </label>
                        <select name="group" class="form-control" id="id_group">
                        <option value="" selected>---------</option>
                        <option value="1">Группа: Лев Толстой – зеркало русской революции</option>
                        </select>
                        <small id="id_group-help" class="form-text text-muted">
                        Группа, к которой будет относиться пост
                        </small>
                    </div>
                {% endif %}
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                        {% if is_edit %}
                            Сохранить
                        {% else %}
                            Добавить
                        {% endif %}
                    </button>
                </div>
                </form>
            </div>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}{{ group.title }}{% endblock %}
{% include 'base.html' %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>
    {{ group.discription }} Группа тайных поклонников графа.
  </p>
  {% for post in page_obj %}
    {% include 'posts/includes/card_post.html' %}
  {% endfor %}
{% endblock %}

yatube/templates/posts/includes/card_post.html
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    <p>{{ post.text }}</p>
  </ul>
  {% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
</article>

yatube/templates/posts/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year_now }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer> 

yatube/templates/posts/includes/header.html
<header>
  {% with request.resolver_match.view_name as view_name %}
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class='navbar-brand' href="{% url 'posts:index' %}">
          <img src="static/img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
          <span style="color:red">Ya</span>tube</a>
        </a>
        <ul class="nav nav-pills">
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
              href="{% url 'about:author' %}"
            >
              Об авторе
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
              href="{% url 'about:tech' %}"
            >
              Технологии
            </a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'posts:create' %}active{% endif %}"
              href="{% url 'posts:post_create' %}"
            >
              Новая запись
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:password_reset' %}active{% endif %}" 
              href="{% url 'users:password_reset' %}"
            >
              Изменить пароль
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}" 
              href="{% url 'users:logout' %}"
            >
              Выйти
            </a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
          {% else %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}" 
              href="{% url 'users:login' %}"
            >
              Войти
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}" 
              href="{% url 'users:signup' %}"
            >
              Регистрация
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  {% endwith %}      
</header>

yatube/templates/posts/includes/paginator.html
{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% include 'base.html' %}
{% block content %}  
  <h1> Главная страница </h1>
  <article>
    {% for post in page_obj %}
      {% include 'posts/includes/card_post.html' %}
    {% endfor %}
  </article>
{% endblock %}      

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}Пост {% endblock %}
{% include 'base.html' %}
{% block content %}
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: <!-- 31 июля 1854 --> 
            </li>
              {% if post.group %}    
                <li class="list-group-item">
                  Группа: {{ group.title }}
                  <a href="{% url 'posts:group_list' post.group.slug %}">
                    все записи группы
                  </a>
                </li>
              {% else %}
                <li class="list-group-item">
                  Группа: Нет группы
                </li>
              {% endif %}
              <li class="list-group-item">
                Автор: {{ post.username }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span ><!-- --></span>
            </li>
            <li class="list-group-item">
              <a href="">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
           <!--
            [Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ 
            Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями.
            Генерал[у] по этому должно быть случаю, угодно было спрашивать о мое
            мъ здоровьи.
            Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за 
            нын[ѣшній]     день. Послѣдній упрекъ становится слишкомъ частъ, 
            хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. 
            Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ 
            жалко бросить штабъ. Здоровье кажется (2) лучше. 
           --> 
          </p>
        </article>
      </div> 
    </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Профайл пользователя{% endblock %}
{% include 'base.html' %}
{% block content %}    
    <h1>Все посты пользователя {{ post.author.get_full_name }}</h1>
    <h3>Всего постов: <!-- --> </h3>   
    <article>
        <ul>
        <li>
            Автор: <!--Лев Толстой-->
            <a href="<!-- -->">все посты пользователя</a>
        </li>
        <li>
            Дата публикации: <!-- 31 июля 1854 --> 
        </li>
        </ul>
        <p>
        <!--
        [Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ 
        Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями.
        Генерал[у] по этому должно быть случаю, угодно было спрашивать о мое
        мъ здоровьи.
        Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за 
        нын[ѣшній]     день. Послѣдній упрекъ становится слишкомъ частъ, 
        хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. 
        Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ 
        жалко бросить штабъ. Здоровье кажется (2) лучше. 
        --> 
        </p>
        <a href="<!-- -->">подробная информация </a>
    </article>       
    <a href="<!-- -->">все записи группы</a>         
{% endblock %}

yatube/templates/posts/update_post.html
{% extends "base.html" %}
{% block title %}Новый пост<!-- Первые 30 букв поста -->{% endblock %}
{% include 'base.html' %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            Редактировать пост             
          </div>
          <div class="card-body">        
            <form method="post" action="../posts/create_post.html">
              <input type="hidden" name="csrfmiddlewaretoken" value="">            
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста                  
                  <span class="required text-danger" >*</span>                  
                </label>
                <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                </textarea>                
                <small id="id_text-help" class="form-text text-muted">
                  Текст нового поста
                </small>                  
              </div>            
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Группа                  
                </label>
                <select name="group" class="form-control" id="id_group">
                  <option value="">---------</option>
                  <option value="1" selected>Группа: Лев Толстой – зеркало русской революции</option>
                </select>
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  Добавить
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/logged_out.html
<title>
  {% block title %}Вы вышли из системы{% endblock %}
</title>
{% include 'base.html' %}
{% block content %}
<article>
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}
{% include 'includes/footer.html' %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Пароль изменён
          </div>
          <div class="card-body"> 
            <p>Пароль изменён успешно</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Восстановление пароля завершено
          </div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="../users/login.html">войти</a>
          </div> 
        </div> 
      </div>
    </div> 
  </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}